shopping_list = []
while True:
    action = input("""What would you like to do?
    
    Enter 1 to add item
    Enter 2 to remove item
    Enter 3 to view list
    Enter 4 to exit:\n""")

    if action == "1":
        item = input("Enter the item to add: ")
        shopping_list.append(item)
        print(f"'{item}' added. Current shopping list:", shopping_list)

    elif action == "2":
        item = input("Enter the item to remove: ")
        if item in shopping_list:
            shopping_list.remove(item)
            print(f"'{item}' removed.shopping list:", shopping_list)
        else:
            print(f"'{item}' is not in the shopping list.")

    elif action == "3":
        print("shopping list:", shopping_list)

    elif action == "4":
        print("Exiting. Have a nice day!")
        break

    else:
        print("Wrong choice. Please try again.")
